### ISSUE TITLE
three-prwm-loader npm package

### ISSUE THREAD

**Issue by ashl1** [kchapelier/PRWM#2]
Do you have any plans to make npm package for `three-prwm-loader`?
Unfortunately `examples/js/loaders/*` aren't available through `three` npm package

**Comment by kchapelier** [comment]
I hesitated to do it at first because the Three.js project has (what I would call) stringent guidelines regarding codestyle and would likely not accept a PR with bundled files. But I understand the issue as I'm mostly using npm modules with browserify. I'll investigate more closely how to do that without having to maintain separate versions of the same code.

**Comment by ashl1** [comment]
Currently I use workaround but don't know is it good solution for packaging:
```javascript
import * as THREE from 'three'

...code of PRWMLoader.js here...

if (typeof exports === 'object') {
  Object.defineProperty(exports, '__esModule', {
    value: true
  })

  exports.default = THREE.PRWMLoader
}

```

**Comment by kchapelier** [comment]
I'd rather not force the user to include three.js as a bundled dependency. The module will probably looks something like this : 

```js
module.exports = function PRWMLoaderWrapper (THREE) {
  ...code of PRWMLoader.js here... 

  return THREE.PRWMLoader;
};
```

So that the require is done like this :

```js
var PRWMLoader = require('three-prwm-loader')(THREE); // wherever THREE may come from
```

or

```js
import PRWMLoaderWrapper from "three-prwm-loader";
const PRWMLoader = PRWMLoaderWrapper(THREE);
```

**Comment by ashl1** [comment]
The PRWMLoader depends on threejs anyway. To not make static dependency could you add [peerDependency](https://docs.npmjs.com/files/package.json#peerdependencies) and hide initialization with threejs inside the module? There are a lot of packages which use the technique.
The user will be warned to install threejs dependency by hand - whichever version he want. You might also enable versin dependencies.
Do you see any disadvantages of this method?

**Comment by kchapelier** [comment]
What I specifically want to avoid is importing/requiring Three.js inside the module because that implies that Three.js will be treated by the whole bundling / transpiling / minifying pipeline every time there is a change in the user project. With big dependencies as Three.js this come at a cost, especially if this is done by a watch task of some sort.

With this kind of dependency injection on the other hand, the user has the flexibility necessary to avoid this, by using a separate bundle containing Three.js (and other big dependencies) that doesn't need to be rebundled as often or by importing Three.js directly in the page with a simple <script> tag.

**Comment by ashl1** [comment]
Maybe I miss some usage. Could you please describe the problematic pipeline and directory structure?

As I understand as the module will be installed in `node_modules` if installed by npm. In most cases the `node_modules` directory is excluded from any bundling, minifying and so on until build release (if we want monofile).
I know about several techniques, requirejs for example but almost all devs supports AMD and CommonJS syntax. Next week I'll provide you universal code that will work for these syntaxes, for load by hand or loaded in module.

The real is that your module depends on ThreeJS. You want to make Dependency Injection, do you?

**Comment by kchapelier** [comment]
The Three.js loader is now available as [three-prwm-loader on npm](https://www.npmjs.com/package/three-prwm-loader).

---

Regarding the pipeline issue with including Three.js as a direct dependency, it is not related to any specific pipeline or directory structure. Sure Three.js will be installed in `node_modules` but as soon as it will be required/imported in the bundled code, it will have to be (for example with a browserify / babel / uglify pipeline) : 

 * Retrieved by browserify
 * Parsed to an AST by babel, before being treated by all the transforms in the babel configuration/preset and then serialized back to code
 * Minified by uglify
 * For a dev build there may additionally be extra work to generate the sourcemap

This work will be done every time the bundle have to be recreated, so every time any files source file is modified. For such a big codebase, it is a relatively costly process. The solution to this is to either make a second bundle with Three.js (along with any big dependency which is rarely modified) or to include Three.js directly in the page with a <script> tag. This dependency injection pattern gives us the flexibility to do that.

When doing creative application / WebGL "experience" / whatnot it is important to be able to iterate very quickly, so having this flexibility is necessary in my opinion.
